### ISSUE TITLE
confusing documentation about capability subtyping

### ISSUE THREAD

**Issue by kcrimson** [ponylang/pony-tutorial#52] opened 2016-03-02 15:16 UTC
Hi,

I think I have found error in documentation, in capability subtyping section, it says:

> ref <: box. A ref guarantees no other actor can read from or write to the object. A box just guarantees no other actor can write to the object, so it's safe to substitute a ref for a box

which is not true for ref, I think you mean iso in place of ref

**Comment by andymcn** [comment] 2016-03-02 17:23
That looks correct to me.

1. A ref guarantees no other actor can read from or write to the object. Correct.
2. A box just guarantees no other actor can write to the object. Correct.
3. It's safe to substitute a ref for a box. Correct.

I suspect the problem is confusion over the definitions of ref and iso.

An iso does not allow any other references to read from or write to that object, regardless of which actor those references are in.

A ref does not allow any references *in another actor* to read from or write to that object, but it does allow references within the current actor to both read from and write to the object.

**Comment by kcrimson** [comment] 2016-03-02 17:26
That was my impression when I first read the docs, and you right, this is problem with wording and definition of iso and ref, it can be confusing for newcomers

**Comment by andymcn** [comment] 2016-03-02 17:46
I agree capabilities can be confusing when you first meet them and I'm sure that the wording of much of our documentation could be improved. If you have suggestions for how to reword the definitions of iso and ref, or this rule or really any of the docs then please let us know.

**Comment by kcrimson** [comment] 2016-03-02 18:27
The problem is that actors and objects are familiar for many, but capabilities are a new concept. I heard about first time when I found Pony. After previous comment I now have this example:

`
use "collections"

class AnObject
  var s : Array[String] = Array[String]

class TheObject
  fun ref fillIn(a : AnObject) =>
    a.s.push("a string")

actor Main
  new create(env : Env) =>
    var anObject = AnObject
    var theObject = TheObject
    theObject.fillIn(consume anObject)
`

I need to consume anObject to compile this example.  The trick is that actually everything in Pony runs in actor :).

The problem is that in http://tutorial.ponylang.org/capabilities/reference-capabilities/ you can find this statement:

> Reference, written ref. This is for references to mutable data structures that are not isolated, in other words "normal" data. If you have a ref variable then you can read and write the data however you like and you can have multiple variables that can access the same data. But you can't share it with other actors.

so "you can read and write data however you like" :) and in this example I am in a context of single actor, so why do I have to consume anObject? Since I cannot send ref to another actor? Just thinking out loud.

**Comment by andymcn** [comment] 2016-03-02 18:40
You don't actually need to consume anObject here at all, since you aren't sending it to another actor (as you only have one).

The problem is that your variables `anObject` and `theObject` aren't `ref`s, they're `iso`s. This is because their types are inferred as the return types of `AnObject.create()` and `TheObejct.create()`, which both return `iso`s. If you state the variables to have `ref` type then everything works:

```pony
use "collections"

class AnObject
  var s : Array[String] = Array[String]

class TheObject
  fun ref fillIn(a : AnObject) =>
    a.s.push("a string")

actor Main
  new create(env : Env) =>
    var anObject: AnObject ref = AnObject
    var theObject: TheObject ref = TheObject
    theObject.fillIn(anObject)
```

We appreciate that inferring `iso` from an implicit `create()` is confusing. We're currently working on a way to fix this.

**Comment by kcrimson** [comment] 2016-03-02 18:44
or I can have explicit constructors with ref capability :)

**Comment by MrMormon** [comment] 2016-05-28 16:14
Is the issue here still subtyping documentation, or the implicit capability defaults? I don't remember if those are completely in the tutorial.

**Comment by jasoncarr0** [comment] 2021-05-07 13:00
Closing via #449

**Closed by jasoncarr0** 2021-05-07 13:00 UTC
